feat(backend): initial scaffolding for isready cmd
teamhanko/hanko pull request #698
Opened 2023-03-25 08:29 UTC by IgnisDa

# Description

This PR introduces the `isready` sucommand for the Hanko CLI.

Fixes #697.

# Implementation

The command takes in the service to check (`public` or `admin`) and makes an HTTP request to the corresponding health endpoint. 

# Tests

Tested manually.

2023-03-26 05:54 UTC, IgnisDa commented
@like-a-bause This is ready to be reviewed.

2023-03-27 09:32 UTC, like-a-bause requested changes

2023-03-27 09:32 UTC, like-a-bause commented on backend/cmd/isready/isready.go
> +			if address[0] == ':' {
You could use net.SplitHostPort() here.

2023-03-27 09:32 UTC, like-a-bause commented on backend/cmd/isready/isready.go
> +				address = "0.0.0.0" + address
I tried this out and it works. However to quote wikipedia:
```
RFC 1122 refers to 0.0.0.0 using the notation {0,0}. It prohibits this as a destination address in [IPv4](https://en.wikipedia.org/wiki/IPv4) and only allows it as a source address under specific circumstances.
```
We would use this as a destination here. Better to just use localhost, then.

2023-03-27 15:48 UTC, like-a-bause commented on backend/cmd/isready/isready.go
> +			res, err := http.Get(requestUrl)
@sonatype-lift ignore

2023-03-27 16:04 UTC, like-a-bause approved these changes

2023-03-27 16:06 UTC, merged