feat(thirdparty): sign in with apple
teamhanko/hanko pull request #748
Opened 2023-04-26 14:33 UTC by lfleischmann

# Description

This PR adds support for `Sign in with Apple`.

Closes #616 

# Implementation

- Add an Apple provider implementation (f51b68d7217f0e51b84be4883a5717ea4a7bb6a8, a4ea3a80f5e071d5b8c9fb7328f23bcd9148a96d, 793971365655f78ba02f55130e9f121a1634a3a9)
- Add a POST `thirdparty/callback` handler that redirects to the GET handler (9b6855d7463677932dd83c5fb9713e621ad9453d, 1def5717c7c2b0a4d8d957d05d4225ca11fa7699)
  - This is required because Apple enforces a form POST response when requesting scopes
- Add the Apple icon to `elements` for display in `Sign in with ...` button (11912dfd1020f14727ccd60b664fa7472185bf45)
- Add a `siwa` command that allows generating client secrets as per [Apple requirements](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens#3262048) (e87b0ece413ee0fd6e6222d5e68bd5da5f20fc77)
- Document `Sign in with apple` in social guide (544d80830807cfa5d81f13d9618f898abb7816c9)

# Tests

Thirdparty handler tests have been extended accordingly.

2023-04-27 13:23 UTC, bjoern-m commented on docs/docs/guides/social/apple.mdx
> +- Create and your Apple credentials and configure them with Hanko.
```suggestion
- Create your Apple credentials and configure them with Hanko.
```

2023-04-27 13:35 UTC, bjoern-m commented on docs/docs/guides/social/apple.mdx
> +  then select `Services IDs` in the dropdown in the right.
```suggestion
  then select `Services IDs` from the dropdown menu on the right.
```

2023-04-28 09:14 UTC, like-a-bause requested changes
Works as intended. I could follow the guide and get it working.

2023-04-28 09:14 UTC, like-a-bause commented on docs/docs/guides/social/apple.mdx
> +  - an`error_redirect_url`: This is a URL in your frontend the Hanko API redirects to if an error occurs during third
```suggestion
  - an `error_redirect_url`: This is a URL in your frontend the Hanko API redirects to if an error occurs during third
```

2023-04-28 10:13 UTC, like-a-bause commented on docs/docs/guides/social/apple.mdx
> +:::caution
I think a Fire would escalated things a little.

2023-04-28 11:31 UTC, merged