added a schedule a demo badge
teamhanko/hanko pull request #880
Opened 2023-06-30 10:02 UTC by PeerRich

increase sales with a scheduling badge

![CleanShot 2023-06-30 at 12 01 49@2x](https://github.com/teamhanko/hanko/assets/8019099/95289368-51bc-4d2e-8a34-e77542fa0214)

2023-07-03 21:43 UTC, FlxMgdnz requested changes

2023-07-03 21:43 UTC, FlxMgdnz commented on README.md
> +Schedule a Hanko Demo. Learn how Hanko will speed up your registration and login flows with passkey.
```suggestion
Schedule a Hanko demo. Learn how Hanko will speed up your registration and login flows with passkeys.
```

2023-07-03 21:44 UTC, FlxMgdnz approved these changes

2023-07-04 08:54 UTC, like-a-bause approved these changes

2023-07-04 08:54 UTC, merged